Update README.md
grafana/tns pull request #29
Opened 2020-09-10 19:48 UTC by aSquare14

2020-09-10 19:49 UTC, aSquare14 commented
@beorn7 @gouthamve Made a minor change to README. Pl review :)

2020-09-11 11:16 UTC, beorn7 requested changes
Based on what we just discussed in the meeting, perhaps it would make sense to add an explicit note in line 18 that the new v3 of k3d works much differently and that it is recommended to stick to v1.6. (Or does v1.7 work even better? That's the last version before they did the v3 rewrite. @aSquare14 which version did you end up using?)

2020-09-11 11:16 UTC, beorn7 commented on README.md
> +If you encounter the error `jb: command not found` after installation add `$(go env GOPATH)/bin` to your `$PATH`.
This sounds like you have built `jb` from sources rather than downloading the binaries from the link given above.

The weird thing about the binaries is that they are not in an archive, but the download is just the one binary file. You have to make it executable (as described in L32) but also rename it to `jb` and move it into a place where your `$PATH` points to.

How about improving the instructions in that direction? Then the reader should be able to download the binary and use it rather than building from sources (which is probably what you have done in the end).

2020-09-11 11:18 UTC, aSquare14 commented
I used v1.6

2020-09-11 12:18 UTC, aSquare14 commented on README.md
> +If you encounter the error `jb: command not found` after installation add `$(go env GOPATH)/bin` to your `$PATH`.
Yes, makes sense. I will update that accordingly.

2020-09-11 14:33 UTC, beorn7 approved these changes
Great. I'll just approve and leave the merging to you so that we can see if you have all the required permissions by now.

2020-09-14 07:44 UTC, merged

2020-09-14 09:07 UTC, beorn7 commented
It worked! :tada: